var config = {
    // 默认的服务地址
    defaultServiceUrl: "http://192.168.8.204:8010/Portal/Mobile",
    //app请求的URL update by ousihang
    defaultAppServerPortal: "http://java.h3bpm.net:8081/Portal",
    defaultAppServiceUrl: "http://java.h3bpm.net:8081/Portal/Mobile",
    defaultAppName: "H3 BPM移动办公",
    // 默认的语言 zh_cn：中文 en_us：English
    //update by ouyangsk PC端为zh_CN,此处应与PC保持一致，18-02-08发现PC端又为zh_cn，与PC端保持同步
    defaultLanguage: 'zh_cn',
    // 默认是否自动登录
    defaultAutoLogin: true,
    // 是否允许修改服务器地址
    defaultAllowModifyService: true,
    // 待办是否显示排序
    defaultUnfinishedWorkItemSortable: false,
    // 默认的用户头像
    defaultImageUrl: "img/user.jpg",
    // 发起流程是否可见
    defaultStartworkflowDisplay: true,
    // 客户端类型
    platform: ["Android", "iOS"],
    //客户端平台:App,微信，钉钉
    loginfrom: "",
    portalroot: "portal",
    // 语言包
    languages: {
        current: {},
        zh: {
            isShow: false,
            back: '返回',
            close: '关闭',
            moreData: '数据加载中...',
            pullingtext: '松开刷新',
            refreshingtext: '努力加载中...',
            filter: '筛选',
            receiveTime: '接收时间：',
            handleTime: '处理时间：',
            cancelTime: '取消时间：',
            noMoreDatas: '没有更多的数据',
            //update by ouyangsk
            readItem: '已阅',
            sampleData: '样例数据',
            checkNetWork: '您处于离线状态，请检查网络',
            loginAgin: '登录超时，请重新登录',
            loginExit: '登录超时，即将退出',
            loginFail: '登录失败，请联系管理员',
            serverError: '远程服务器连接错误，请稍后再试',
            personTotal: '人',
            setSuccess: '设置成功',
            setFailed: '设置失败',
            ipError: 'ip不合法',
            infoNotLeal: '存在不合法内容',
            reset: '重置',
            confirm: '确定',
            loginOut: '退出',
            checkNewVersion: '检测到新版本',
            enterUserName: '请输入账号',
            enterPassword: '请输入密码',
            loginError: '账号或密码不对！',
            tabs: {
                home: '首页',
                InitiateProcess: '发起流程',
                myProcess: '我的流程',
                report: "报表",
                apps: "应用中心"
            },
            tabHome: {
                tab: ['待办', '待阅', '已办', '已阅'],
                setting: '设置',
                batchRead: '批量阅读',
                cancel: '取消',
                confirm: '确定',
                all: '全选',
            },
            tabMyInstances: {
                tab: ['常用', '全部'],
                setFrequent: '设置常用成功',
                cancelFrequent: '取消常用成功',
                searchProcessname: '搜索流程名称',
            },
            tabMyProcess: {
                tab: ['进行中', '已完成', '已取消'],
            },
            Filter: {
                processName: '流程名称',
                processNames: '请输入流程名称',
                originator: '发起人',
                createdTime: '创建日期',
                star: '初始时间',
                end: '结束时间',
                urgent: '是否加急',
                yes: '是',
                no: '否',
                all: '不限',
            },
            setting: {
                currentVersion: '当前版本',
                IP: 'IP/域名',
                languageSetting: '切换语言',
                systemSetting: '系统设置',
            },
            login: {
                antoLoading: '自动登录',
                systemSetting: '系统设置',
                Loading: '登录',
                name: '请输入账号',
                password: '请输入密码',
            },
            sheetUser: {
                organnizationName: '发起人',
                organnization: '组织机构',
                departmentStaff: '本部门',
                search: '搜索',
                checkAll: '全选',
                user: '人员',
                result: '',
            },
            report: {
                ProcessName: "流程名称",
                WorkFlow: "流程模板",
                Originator: "发起人",
                StartTime: "开始时间",
                EndTime: "结束时间",
                Unfinished: "进行中",
                Finished: "已完成",
                Canceled: "已取消",
                Unspecified: "全部",
                sInfo: "当前从第 _START_ 到第 _END_ 项，总共有 _TOTAL_ 项",
                sProcessing: "正在努力加载...",
                search: "搜索...",
                sZeroRecords_NoRecords: "没有满足条件的记录",
                sLengthMenu: "每页显示 _MENU_ 条记录",
                QueryInstanceByProperty_NotEnoughAuth1: "权限不足：流程模板参数为空，表示要查询出指定组织结构发起的所有流程，在这种情况下，要求您具有查看该组织发起的所有流程的权限。",
                QueryInstanceByProperty_NotEnoughAuth2: "权限不足：您不具有查看该组织结构发起的该类型的流程",
                QueryInstanceByProperty_NotEnoughAuth3: "权限不足：审批人参数为空，表示要查询出所有组织发起的流程，在这种情况下，要求您具有查看所有组织发起的该流程的权限。",
            },
            //update by ouyangsk
            dateInError: "时间区间错误"
        },
        en: {
            isShow: true,
            back: 'Back',
            close: 'Close',
            moreData: 'Data loading…',
            pullingtext: 'Refresh after release',
            refreshingtext: 'Refreshing...',
            filter: 'Filter',
            receiveTime: 'ReceiveTime：',
            handleTime: 'HandleTime：',
            cancelTime: 'CancelTime：',
            noMoreDatas: 'No more datas',
            //update by ouyangsk
            readItem: 'Read',
            sampleData: 'sampleData',
            reset: 'Reset',
            confirm: 'Confirm',
            loginOut: 'LogOut',
            setFailed: 'Set failed',
            setSuccess: 'Set successfully',
            ipError: 'Illegal IP',
            infoNotLeal: 'some info not legal',
            checkNetWork: 'You are offline，please check the network',
            loginAgin: 'Login timeout，Please login again',
            loginExit: 'Login timeout，exit',
            personTotal: 'person in total',
            serverError: 'Remote server connection error，please try again later',
            loginFail: 'Login fail，please contact the administrator',
            enterUserName: 'Please enter the userName',
            enterPassword: 'Please enter the password',
            checkNewVersion: 'detect the new version',
            loginError: 'Incorrect username or password',
            tabs: {
                home: 'HomePage',
                InitiateProcess: 'Initiate process',
                myProcess: 'My process',
                report: "Reporting",
                apps: "appCenter"
            },
            tabHome: {
                tab: ['To-do task', 'To-read task', 'Finished task', 'Finished read'],
                setting: 'Setting',
                batchRead: 'Batch',
                cancel: 'Cancel',
                confirm: 'Confirm',
                all: 'All',
            },
            tabMyInstances: {
                tab: ['Frequent Flow', 'All'],
                setFrequent: 'Set up frequent flow succeed',
                cancelFrequent: 'Cancel frequent flow succeed',
                searchProcessname: 'Search processname',
            },
            tabMyProcess: {
                tab: ['Unfinished', 'Finished', 'Canceled'],
            },
            Filter: {
                processName: 'ProcessName',
                processNames: 'ProcessName please',
                originator: 'Originator',
                createdTime: 'CreatedTime',
                star: 'Initial Time',
                end: 'Endtime',
                urgent: 'Urgent',
                yes: 'Yes',
                no: 'No',
                all: 'All',
            },
            setting: {
                currentVersion: 'Current version',
                IP: 'IP/Domain Name',
                languageSetting: 'Language setting',
                systemSetting: 'System setting',
            },
            login: {
                antoLoading: 'Auto',
                systemSetting: 'System setting',
                Loading: 'Login',
                name: 'UserName',
                password: 'Password',
            },
            sheetUser: {
                organnization: 'Organnization',
                departmentStaff: 'Department Staff',
                search: 'Search',
                checkAll: 'Check all',
                user: 'Personnel',
                result: 'No results related to',
                organnizationName: 'Originator',
            },
            report: {
                ProcessName: "ProcessName",
                WorkFlow: "WorkFlow",
                Originator: "Originator Scope",
                StartTime: "Start time",
                EndTime: "End time",
                Unfinished: "Unfinished",
                Finished: "Finished",
                Canceled: "Canceled",
                Unspecified: "Total",
                sInfo: "Showing _START_ to _END_ of _TOTAL_ entries",
                sProcessing: "Loading...",
                search: "search...",
                sZeroRecords_NoRecords: "No Found Records",
                sLengthMenu: "Show _MENU_ entries",
                QueryInstanceByProperty_NotEnoughAuth1: "Not enough authorization: please select one workflow scope.",
                QueryInstanceByProperty_NotEnoughAuth2: "Not enough authorization: you can not view the flows originated by the selected organization.",
                QueryInstanceByProperty_NotEnoughAuth3: "Not enough authorization: if you are the administrator of the selected workflow, please select one organization scope."
            },
            dateInError: "Date Interval Error"
        }
    }
}